enums = {}

enums.format = [
  '8 mm',
  '16 mm',
  '35 mm',
  '70 mm',
  'Blu-ray Disc',
  'CDKuva',
  'DCP',
  'DVD',
  'Televisio',
  'Verkkoaineisto',
  'VHS',
  'video',
  'VoD',
  'Muu'
]

enums.programType = {
  1: 'Kotimainen elokuva',
  2: 'Ulkomainen elokuva',
  '2b': 'TESTI',
  3: 'TV-sarjan jakso',
  4: 'Muu tv-ohjelma',
  5: 'TV-sarjan nimi',
  6: 'Traileri',
  7: 'Extra',
  8: 'Peli',
  10: 'Yhteistuotanto',
  11: 'PEGI hyväksytty peli',
  12: 'Muu kuvaohjelma'
}

enums.countries = {
  'AE': 'Arabiemiirikunnat',
  'AF': 'Afganistan',
  'AL': 'Albania',
  'AR': 'Argentiina',
  'AT': 'Itävalta',
  'AU': 'Australia',
  'BA': 'Bosnia-Hertsegovina',
  'BD': 'Bangladesh',
  'BE': 'Belgia',
  'BG': 'Bulgaria',
  'BH': 'Bhutan',
  'BM': 'Bermuda',
  'BO': 'Bolivia',
  'BR': 'Brasilia',
  'BT': 'Bhutan',
  'BY': 'Valko-Venäjä',
  'CA': 'Kanada',
  'CH': 'Sveitsi',
  'CL': 'Chile',
  'CM': 'Kamerun',
  'CN': 'Kiina',
  'CO': 'Kolumbia',
  'CR': 'Costa Rica',
  'CS': 'Serbia / Tsekkoslovakia',
  'CU': 'Kuuba',
  'CY': 'Kypros',
  'CZ': 'Tsekinmaa',
  'DD': 'Itä-Saksa',
  'DE': 'Saksa',
  'DK': 'Tanska',
  'DZ': 'Algeria',
  'EC': 'Ecuador',
  'EE': 'Viro',
  'EG': 'Egypti',
  'ES': 'ES',
  'ET': 'Etiopia',
  'EU': 'Euroopan unioni',
  'FI': 'Suomi',
  'FO': 'Fär-saaret',
  'FR': 'Ranska',
  'GB': 'Iso-Britannia',
  'GL': 'Grönlanti',
  'GN': 'Guinea',
  'GR': 'Kreikka',
  'GT': 'Guatemala',
  'HK': 'Hongkong',
  'HR': 'Kroatia',
  'HU': 'Unkari',
  'ID': 'Indonesia',
  'IE': 'Irlanti',
  'IL': 'Israel',
  'IN': 'Intia',
  'IQ': 'Irak',
  'IR': 'Iran',
  'IS': 'Islanti',
  'IT': 'Italia',
  'JM': 'Jamaika',
  'JO': 'Jordania',
  'JP': 'Japani',
  'KN': 'Kenia',
  'KP': 'Pohjois-Korea',
  'KR': 'Etelä-Korea',
  'LA': 'Laos',
  'LB': 'Libanon',
  'LI': 'Lichtenstein',
  'LK': 'Sri Lanka',
  'LT': 'Liettua',
  'LU': 'Luxemburg',
  'LV': 'Latvia',
  'MA': 'Marokko',
  'MC': 'Monaca',
  'ML': 'Mali',
  'MN': 'Mongolia',
  'MR': 'Mauritania',
  'MT': 'Malta',
  'MU': 'Mauritius',
  'MX': 'Meksiko',
  'MY': 'Malesia',
  'MZ': 'Mosambik',
  'NA': 'Namibia',
  'NE': 'Niger',
  'NG': 'Nigeria',
  'NI': 'Nicaragua',
  'NL': 'Alankomaat',
  'NO': 'Norja',
  'NP': 'Nepal',
  'NZ': 'Uusi-Seelanti',
  'PE': 'Peru',
  'PH': 'Filippiinit',
  'PK': 'Pakistan',
  'PL': 'Puola',
  'PR': 'Puerto Rico',
  'PT': 'Portugali',
  'PY': 'Paraguay',
  'RO': 'Romania',
  'RU': 'Venäjä',
  'SD': 'Sudan',
  'SE': 'Ruotsi',
  'SG': 'Singapore',
  'SI': 'Slovenia',
  'SK': 'Slovakia',
  'SN': 'Senegal',
  'SU': 'Neuvostoliitto',
  'SV': 'El Salvador',
  'SY': 'Syyria',
  'TH': 'Thaimaa',
  'TN': 'Tunisia',
  'TR': 'Turkki',
  'TW': 'Taiwan',
  'TZ': 'Tansania',
  'US': 'Yhdysvallat',
  'UY': 'Uruguay',
  'VA': 'Vatikaanivaltio',
  'VE': 'Venezuela',
  'VN': 'Vietnam',
  'YU': 'Jugoslavia',
  'ZA': 'Etelä-Afrikka',
  'ZM': 'Sambia',
  'ZW': 'Zimbabwe',
  '-': 'Muu maa'
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = enums
}